#!/usr/bin/ansible-playbook -K
---
- name: configures xmonad
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      become: yes
      with_items:
        - xmonad
        - alsa-utils
        - dzen2
        - cabal-install
        - feh
        - ghc
        - kitty
        - murrine-themes
        - network-manager
        - network-manager-gnome
        - network-manager-openvpn
        - network-manager-openvpn-gnome
        - pavucontrol
        - stalonetray
        - suckless-tools
        - xbacklight
        - xcape
        - xdotool
        - xfce4-appfinder
        - xmobar
        - xscreensaver
        - xss-lock

        # Dependencies for statnot
        - python-dbus

    - name: compile xmonad config
      shell: xmonad --recompile

    # Install fonts
    - name: create font directory
      file: path=~/.fonts state=directory
    - name: install powerline fonts
      git: repo=git@github.com:Lokaltog/powerline-fonts.git
           dest=~/.fonts/powerline-fonts
           update=no
