#!/usr/bin/env ansible-playbook
---
- name: configures xmonad
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      sudo: yes
      with_items:
        - haskell-platform
        - xmonad
        - alsa-utils
        - dzen2
        - murrine-themes
        - rxvt-unicode
        - stalonetray
        - suckless-tools
        - xbacklight
        - xdotool
        - xscreensaver

        # These are dependencies of xmonad and xmonad-related cabal
        # packages.
        - libxinerama-dev
        - libxrandr-dev
        - libxss-dev
        # - libxft2-dev
        - pkg-config

    - name: the ansible module seems to have problems with libxft2-dev
      shell: apt-get install libxft2-dev
      sudo: yes

    - name: cabal update
      shell: cabal update

    # xmonad-contrib and xmonad-extras are dependencies of my xmonad
    # configuration.
    #
    # xmonad-utils provides the hhp utility, which hides the mouse
    # pointer when it is not being actively used.
    - name: install xmonad
      shell: cabal install xmonad xmonad-contrib xmonad-extras xmonad-utils xmobar yeganesh
             creates=~/.cabal/bin/xmonad

    - name: compile xmonad config
      shell: xmonad --recompile

    - name: ensure local Xresources config file is present
      file: path=~/.config/Xresources/local state=touch

    # Install fonts
    - name: create font directory
      file: path=~/.fonts state=directory
    - name: install powerline fonts
      git: repo=git@github.com:Lokaltog/powerline-fonts.git
           dest=~/.fonts/powerline-fonts
           update=no
