#!/usr/bin/ansible-playbook -K
---
- name: configures xmonad
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      sudo: yes
      with_items:
        - haskell-platform
        - xmonad
        - alsa-utils
        - dzen2
        - murrine-themes
        - rxvt-unicode
        - stalonetray
        - suckless-tools
        - unclutter
        - xbacklight
        - xdotool
        - xscreensaver

        # These are dependencies of xmonad and xmonad-related cabal
        # packages.
        - libxinerama-dev
        - libxrandr-dev
        - libxss-dev
        # - libxft2-dev
        - pkg-config

    - name: the ansible module seems to have problems with libxft2-dev
      shell: apt-get install libxft2-dev
      sudo: yes

    - name: cabal update
      shell: cabal update

    - name: install xmonad
      shell: cabal install xmonad xmonad-contrib xmonad-extras xmobar yeganesh
             creates=~/.cabal/bin/xmonad

    - name: compile xmonad config
      shell: xmonad --recompile

    # Install fonts
    - name: create font directory
      file: path=~/.fonts state=directory
    - name: install powerline fonts
      git: repo=git@github.com:Lokaltog/powerline-fonts.git
           dest=~/.fonts/powerline-fonts
           update=no

    - file: path=/usr/local/lib/urxvt state=directory
      sudo: yes
    - name: install extensions for urxvt
      git: repo=https://github.com/muennich/urxvt-perls.git
           dest=/usr/local/lib/urxvt/perl
           update=no
      sudo: yes
