#!/usr/bin/ansible-playbook -K
---
- name: configures xmonad
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      become: yes
      with_items:
        - xmonad
        - libghc-xmonad-contrib-dev
        - alsa-utils
        - dzen2
        - cabal-install
        - feh
        - ghc
        - ghc-mod
        - murrine-themes
        - network-manager
        - network-manager-gnome
        - network-manager-openvpn
        - network-manager-openvpn-gnome
        - rxvt-unicode
        - stalonetray
        - suckless-tools
        - xbacklight
        - xdotool
        - xfce4-appfinder
        - xmobar
        - xscreensaver
        - xss-lock

        # Dependencies for config-reload extension for urxvt
        - libanyevent-perl
        - libcommon-sense-perl
        - liblinux-fd-perl
        - liblog-log4perl-perl

    - name: compile xmonad config
      shell: xmonad --recompile

    # Install fonts
    - name: create font directory
      file: path=~/.fonts state=directory
    - name: install powerline fonts
      git: repo=git@github.com:Lokaltog/powerline-fonts.git
           dest=~/.fonts/powerline-fonts
           update=no

    - file: path=/usr/local/lib/urxvt state=directory
      become: yes
    - name: install extensions for urxvt
      git: repo=https://github.com/muennich/urxvt-perls.git
           dest=/usr/local/lib/urxvt/perl
           update=no
      become: yes
